# 配置示例文件
# 请复制此文件并重命名为 application-local.yml，然后填入真实的配置信息

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yunlog?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: your_password_here

# 阿里云 OSS 配置
aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: YOUR_ACCESS_KEY_ID
    access-key-secret: YOUR_ACCESS_KEY_SECRET
    bucket-name: yunmem
    url-prefix: https://yunmem.oss-cn-beijing.aliyuncs.com/
    folder: diary/images/
